### PR TITLE
Generalize elastic constant conversion

### LINKED ISSUE #182: LinearCombination does not work with nonlinear parameter
coefficients in LinearCombination do not take nonlinear parameters.

### PR DESCRIPTION
**Pull request by hugary1995**
- Separate out conversion functions for elastic constants so that they could be reused elsewhere independent of the models
- Fix cross-referencing when declare nonlinear parameter -- same change applied to BufferStore
- Separate out generic converters for better code reuse: see `ElasticityConverter.h`
- Do not calculate derivatives if the input elastic constants are not nonlinear parameters
- Move all elasticity-related models into the `elasticity` subfolder

### CODE REVIEW

File: include/neml2/models/solid_mechanics/elasticity/ElasticityTensor.h [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+
+namespace neml2
+{
+template <class Derived, std::size_t N>
+OptionSet
+ElasticityTensor<Derived, N>::expected_options()
+{
+  OptionSet options = Derived::expected_options();
+
+  MultiEnumSelection type_selection({"LAME_FIRST_CONSTANT",
```
Comment (reverendbedford) [inline include/neml2/models/solid_mechanics/elasticity/ElasticityTensor.h]: Honestly `"LAME_LAMBDA"` may be better.  This always makes me have to think about which is the first parameter...

File: include/neml2/models/solid_mechanics/elasticity/ElasticityConverter.h [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+      input_values[i] = *input[i];
+    return convert(input_values);
+  }
+
+private:
+  /// Generate ordering of the input parameters
+  void assert_ascending(const ConverterKey & ps) const
+  {
+    for (std::size_t i = 1; i < N; ++i)
+      neml_assert(
```
Comment (reverendbedford) [inline include/neml2/models/solid_mechanics/elasticity/ElasticityConverter.h]:
```suggestion
      neml_assert_debug(
```

I assume, as this is an internal error.

**Review by reverendbedford — CHANGES_REQUESTED** [review]

File: include/neml2/models/solid_mechanics/elasticity/ElasticityConverter.h (hunk 2 above)
Comment (hugary1995) [reply include/neml2/models/solid_mechanics/elasticity/ElasticityConverter.h]: This is internal. But I think it doesn't hurt to make this check a non `_dbg` one, because it's only called in the constructor and doesn't affect run speed.

**Comment by hugary1995** [comment]
Don't merge yet, one last change tomorrow morning.

File: include/neml2/models/solid_mechanics/elasticity/ElasticityConverter.h (hunk 2 above)
Comment (reverendbedford) [reply include/neml2/models/solid_mechanics/elasticity/ElasticityConverter.h]: Okay.

**Review by reverendbedford — APPROVED** [review]
